# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/src/qgis/python/plugins/db_manager/ui/DlgTableProperties.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DbManagerDlgTableProperties(object):
    def setupUi(self, DbManagerDlgTableProperties):
        DbManagerDlgTableProperties.setObjectName("DbManagerDlgTableProperties")
        DbManagerDlgTableProperties.resize(547, 435)
        self.vboxlayout = QtWidgets.QVBoxLayout(DbManagerDlgTableProperties)
        self.vboxlayout.setObjectName("vboxlayout")
        self.tabs = QtWidgets.QTabWidget(DbManagerDlgTableProperties)
        self.tabs.setObjectName("tabs")
        self.tabColumns = QtWidgets.QWidget()
        self.tabColumns.setObjectName("tabColumns")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.tabColumns)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.label = QtWidgets.QLabel(self.tabColumns)
        self.label.setObjectName("label")
        self.vboxlayout1.addWidget(self.label)
        self.viewFields = QtWidgets.QTreeView(self.tabColumns)
        self.viewFields.setRootIsDecorated(False)
        self.viewFields.setObjectName("viewFields")
        self.vboxlayout1.addWidget(self.viewFields)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.btnAddColumn = QtWidgets.QPushButton(self.tabColumns)
        self.btnAddColumn.setObjectName("btnAddColumn")
        self.hboxlayout.addWidget(self.btnAddColumn)
        self.btnAddGeometryColumn = QtWidgets.QPushButton(self.tabColumns)
        self.btnAddGeometryColumn.setObjectName("btnAddGeometryColumn")
        self.hboxlayout.addWidget(self.btnAddGeometryColumn)
        self.btnEditColumn = QtWidgets.QPushButton(self.tabColumns)
        self.btnEditColumn.setObjectName("btnEditColumn")
        self.hboxlayout.addWidget(self.btnEditColumn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnDeleteColumn = QtWidgets.QPushButton(self.tabColumns)
        self.btnDeleteColumn.setObjectName("btnDeleteColumn")
        self.hboxlayout.addWidget(self.btnDeleteColumn)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.tabs.addTab(self.tabColumns, "")
        self.tabConstraints = QtWidgets.QWidget()
        self.tabConstraints.setObjectName("tabConstraints")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.tabConstraints)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.label_3 = QtWidgets.QLabel(self.tabConstraints)
        self.label_3.setObjectName("label_3")
        self.vboxlayout2.addWidget(self.label_3)
        self.viewConstraints = QtWidgets.QTreeView(self.tabConstraints)
        self.viewConstraints.setRootIsDecorated(False)
        self.viewConstraints.setObjectName("viewConstraints")
        self.vboxlayout2.addWidget(self.viewConstraints)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.btnAddConstraint = QtWidgets.QPushButton(self.tabConstraints)
        self.btnAddConstraint.setObjectName("btnAddConstraint")
        self.hboxlayout1.addWidget(self.btnAddConstraint)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.btnDeleteConstraint = QtWidgets.QPushButton(self.tabConstraints)
        self.btnDeleteConstraint.setObjectName("btnDeleteConstraint")
        self.hboxlayout1.addWidget(self.btnDeleteConstraint)
        self.vboxlayout2.addLayout(self.hboxlayout1)
        self.tabs.addTab(self.tabConstraints, "")
        self.tabIndexes = QtWidgets.QWidget()
        self.tabIndexes.setObjectName("tabIndexes")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.tabIndexes)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.label_2 = QtWidgets.QLabel(self.tabIndexes)
        self.label_2.setObjectName("label_2")
        self.vboxlayout3.addWidget(self.label_2)
        self.viewIndexes = QtWidgets.QTreeView(self.tabIndexes)
        self.viewIndexes.setRootIsDecorated(False)
        self.viewIndexes.setObjectName("viewIndexes")
        self.vboxlayout3.addWidget(self.viewIndexes)
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.btnAddIndex = QtWidgets.QPushButton(self.tabIndexes)
        self.btnAddIndex.setObjectName("btnAddIndex")
        self.hboxlayout2.addWidget(self.btnAddIndex)
        self.btnAddSpatialIndex = QtWidgets.QPushButton(self.tabIndexes)
        self.btnAddSpatialIndex.setObjectName("btnAddSpatialIndex")
        self.hboxlayout2.addWidget(self.btnAddSpatialIndex)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem2)
        self.btnDeleteIndex = QtWidgets.QPushButton(self.tabIndexes)
        self.btnDeleteIndex.setObjectName("btnDeleteIndex")
        self.hboxlayout2.addWidget(self.btnDeleteIndex)
        self.vboxlayout3.addLayout(self.hboxlayout2)
        self.tabs.addTab(self.tabIndexes, "")
        self.vboxlayout.addWidget(self.tabs)
        self.buttonBox = QtWidgets.QDialogButtonBox(DbManagerDlgTableProperties)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(DbManagerDlgTableProperties)
        self.tabs.setCurrentIndex(0)
        self.buttonBox.accepted.connect(DbManagerDlgTableProperties.accept)
        self.buttonBox.rejected.connect(DbManagerDlgTableProperties.reject)
        QtCore.QMetaObject.connectSlotsByName(DbManagerDlgTableProperties)
        DbManagerDlgTableProperties.setTabOrder(self.tabs, self.viewFields)
        DbManagerDlgTableProperties.setTabOrder(self.viewFields, self.btnAddColumn)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddColumn, self.btnAddGeometryColumn)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddGeometryColumn, self.btnEditColumn)
        DbManagerDlgTableProperties.setTabOrder(self.btnEditColumn, self.btnDeleteColumn)
        DbManagerDlgTableProperties.setTabOrder(self.btnDeleteColumn, self.viewConstraints)
        DbManagerDlgTableProperties.setTabOrder(self.viewConstraints, self.btnAddConstraint)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddConstraint, self.btnDeleteConstraint)
        DbManagerDlgTableProperties.setTabOrder(self.btnDeleteConstraint, self.viewIndexes)
        DbManagerDlgTableProperties.setTabOrder(self.viewIndexes, self.btnAddIndex)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddIndex, self.btnAddSpatialIndex)
        DbManagerDlgTableProperties.setTabOrder(self.btnAddSpatialIndex, self.btnDeleteIndex)
        DbManagerDlgTableProperties.setTabOrder(self.btnDeleteIndex, self.buttonBox)

    def retranslateUi(self, DbManagerDlgTableProperties):
        _translate = QtCore.QCoreApplication.translate
        DbManagerDlgTableProperties.setWindowTitle(_translate("DbManagerDlgTableProperties", "Table properties"))
        self.label.setText(_translate("DbManagerDlgTableProperties", "Table columns:"))
        self.btnAddColumn.setText(_translate("DbManagerDlgTableProperties", "Add column"))
        self.btnAddGeometryColumn.setText(_translate("DbManagerDlgTableProperties", "Add geometry column"))
        self.btnEditColumn.setText(_translate("DbManagerDlgTableProperties", "Edit column"))
        self.btnDeleteColumn.setText(_translate("DbManagerDlgTableProperties", "Delete column"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabColumns), _translate("DbManagerDlgTableProperties", "Columns"))
        self.label_3.setText(_translate("DbManagerDlgTableProperties", "Primary, foreign keys, unique and check constraints:"))
        self.btnAddConstraint.setText(_translate("DbManagerDlgTableProperties", "Add primary key / unique"))
        self.btnDeleteConstraint.setText(_translate("DbManagerDlgTableProperties", "Delete constraint"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabConstraints), _translate("DbManagerDlgTableProperties", "Constraints"))
        self.label_2.setText(_translate("DbManagerDlgTableProperties", "Indexes defined for this table:"))
        self.btnAddIndex.setText(_translate("DbManagerDlgTableProperties", "Add index"))
        self.btnAddSpatialIndex.setText(_translate("DbManagerDlgTableProperties", "Add spatial index"))
        self.btnDeleteIndex.setText(_translate("DbManagerDlgTableProperties", "Delete index"))
        self.tabs.setTabText(self.tabs.indexOf(self.tabIndexes), _translate("DbManagerDlgTableProperties", "Indexes"))

